apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sporenstreks-frontend
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
spec:
  image: {{ image }}
  port: 9000
  liveness:
    path: /health/is-alive
    initialDelay: 15
    timeout: 1
    periodSeconds: 3
    failureThreshold: 10
  readiness:
    path: /health/is-ready
    initialDelay: 15
    timeout: 1
    periodSeconds: 3
    failureThreshold: 10
  ingresses:
    - https://arbeidsgiver-q.nav.no/nettrefusjon/
    - https://arbeidsgiver-nettrefusjon.dev.nav.no
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 800m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 256Mi
  vault:
    enabled: true
    paths:
      - kvPath: apikey/apigw/dev/sporenstreks/sporenstreks-frontend_q1
        mountPath: /apigw/sporenstreks
  env:
    - name: API_GATEWAY
      value: https://api-gw-q1.oera.no/sporenstreks
