name: CI

on:
  push:
    branches:
      - main

env:
  IMAGE: ghcr.io/${{ github.repository }}/sporenstreks-frontend:${{ github.sha }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:

  Bygg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm ci
      - run: npm run-script build
      - uses: actions/upload-artifact@v2
        with:
          name: sporenstreks-frontend-artifact
          path: ${{ github.workspace }}/build/**/*

  Kodekvalitet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci --no-build
      - run: npm test
      - run: node run-sonar.js

  Eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run-script lint

  Snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master

  Docker:
    needs: [Bygg,Kodekvalitet,Eslint,Snyk]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v2
        with:
          name: sporenstreks-frontend-artifact
          path: build
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish Docker image
        run: |
          docker build --tag ${IMAGE} .
          docker push ${IMAGE}

  Deploy:
    name: Deploy til PREPROD
    needs: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          TEAM: helsearbeidsgiver
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-sbs
          RESOURCE: deploy/dev.yaml
