name: Publish

on:
  release:
    types: [published]

env:
  IMAGE: ghcr.io/navikt/sporenstreks-frontend:${{ github.sha }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:

  Bygg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm ci
      - run: npm run-script build
      - uses: actions/upload-artifact@v2
        with:
          name: sporenstreks-frontend-artifact
          path: ${{ github.workspace }}/build/**/*

  Kodekvalitet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci --no-build
      - run: npm test
      - run: node run-sonar.js

  Eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run-script lint

  Snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master

  Docker:
    runs-on: ubuntu-latest
    needs: [Bygg,Kodekvalitet,Eslint,Snyk]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/download-artifact@v2
        with:
          name: sporenstreks-frontend-artifact
          path: build
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_PUSH_USERNAME }}
          password: ${{ secrets.GHCR_PUSH_TOKEN }}
      - name: Build and publish Docker image
        run: |
          docker build --pull --tag ${{ env.IMAGE }}  .
          docker push ${{ env.IMAGE }}

  Deploy:
    name: Deploy
    needs: [Docker]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/download-artifact@v2
        with:
          name: sporenstreks-frontend-artifact
          path: build
      - run: |
          git config --global user.email "helsearbeidsgiver@nav.no"
          git config --global user.name "HelseArbeidsgiver"
          npm version ${{ github.event.release.tag_name }}
          git push origin HEAD:main
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-sbs
          RESOURCE: deploy/prod.yaml
