name: End-to-End Tests
on: [push]

jobs:
  test:
    name: Run TestCafe Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1
      - run: npm ci
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
            skip-install: true
            args: chrome:headless tests/ --app-init-delay 60000 --app "npm run start" --cache
